version: "3.8"

networks:
  traefik:
    name: traefik

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/florent/docker/portainer/data:/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - 90:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - 9010:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@local.dev
      - PGADMIN_DEFAULT_PASSWORD=password

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 81:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    command:
      - --accesslog=true
      - --accesslog.filepath=/var/log/access.log
      - --accesslog.filters.statuscodes=400-499
      - --global.sendAnonymousUsage=false
      - --global.checknewversion=false
      - --log.level=DEBUG
      - --metrics.prometheus=false
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      - --providers.file.directory=/etc/traefik/config
      - --providers.file.watch=true
      - --entrypoints.http=true
      - --entrypoints.http.address=:80
      - --entrypoints.https=true
      - --entrypoints.https.address=:443
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # - --entrypoints.web.http.redirections.entrypoint.permanent=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/florent/docker/traefik/ssl/:/tools/certs:ro
      - /home/florent/docker/traefik/localhost-socgen-com.yml:/etc/traefik/config/localhost-socgen-com.yml:ro
      - /home/florent/docker/traefik/traefik.certs.yml:/etc/traefik/config/certs.yml:ro
